# -*- coding: utf-8 -*-
"""two_tellers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16DkYMU6yQklCm8dvDQXQr09ezzSDPBJ1
"""

import random as rd

# random number generation for Ordinary Customer inter-arrival time
def generate_Ordinary_Customer_IAT():
  r = rd.uniform(0,1)
  if r>=0 and r<0.09:
       IAT = 0
  elif r>=0.09 and r<0.26:
       IAT = 1                              
  elif r>=0.26 and r<0.53:
       IAT = 2
  elif r>=0.53 and r<0.73:
       IAT = 3
  elif r>=0.73 and r<0.88:
       IAT = 4
  elif r>=0.88 and r<1:
       IAT = 5
  return IAT

# random number generation for Ordinary Customer service time
def generate_Ordinary_Customer_ST():
  r = rd.uniform(0,1)
  if r>=0 and r<0.2:
       ST=1
  elif r>=0.2 and r<0.6:
       ST=2                              
  elif r>=0.6 and r<0.88:
       ST=3
  elif r>=0.88 and r<1:
       ST=4
  return ST

# random number generation for Distinguished Customer inter-arrival time
def generate_Distinguished_Customer_IAT():
    r = rd.uniform(0,1)
    if r>=0 and r<0.1:
       IAT=1
    elif r>=0.1 and r<0.3:
       IAT=2                              
    elif r>=0.3 and r<0.6:
       IAT=3
    elif r>=0.6 and r<1:
       IAT=4
    return IAT

# random number generation for Distinguished Customer service time
def generate_Distinguished_Customer_ST():
    r = rd.uniform(0,1)
    if r>=0 and r<0.1:
       ST=1
    elif r>=0.1 and r<0.4:
       ST=2                             
    elif r>=0.4 and r<0.78:
       ST=3
    elif r>=0.78 and r<1:
       ST=4
    return ST

#initialize array for each input variable for both types
Ordinary_Customer_IAT = list()
Ordinary_Customer_ST = list()

Distinguished_Customer_IAT = list() 
Distinguished_Customer_ST = list()

# generate random IAT, ST for 1000 customers for both types
for i in range (1000) : 
  Ordinary_Cust_IAT = generate_Ordinary_Customer_IAT()
  Ordinary_Cust_ST = generate_Ordinary_Customer_ST()
  Distinguished_Cust_IAT = generate_Distinguished_Customer_IAT()
  Distinguished_Cust_ST = generate_Distinguished_Customer_ST()
  
  Ordinary_Customer_IAT.append(Ordinary_Cust_IAT)
  Ordinary_Customer_ST.append(Ordinary_Cust_ST)
  Distinguished_Customer_IAT.append(Distinguished_Cust_IAT)
  Distinguished_Customer_ST.append(Distinguished_Cust_ST)

#initialize array for each variable for both types
Ordinary_Customer_AT = []
Ordinary_Customer_SST = []
Ordinary_Customer_WT = []
Ordinary_Customer_CT = []

Distinguished_Customer_AT = []
Distinguished_Customer_SST = []
Distinguished_Customer_WT = []
Distinguished_Customer_CT = []

# calculate AT, SST, WT, CT for 1000 customers
for i in range(1000):
  # calculations for first customer
  if(i == 0):
    Ordinary_Customer_AT.append(Ordinary_Customer_IAT[i])
    Ordinary_Customer_SST.append(Ordinary_Customer_IAT[i])
    Ordinary_Customer_WT.append(0)
    Ordinary_Customer_CT.append(Ordinary_Customer_SST[i]+Ordinary_Customer_ST[i])

    Distinguished_Customer_AT.append(Distinguished_Customer_IAT[i])
    Distinguished_Customer_SST.append(Distinguished_Customer_IAT[i])
    Distinguished_Customer_WT.append(0)
    Distinguished_Customer_CT.append(Distinguished_Customer_SST[i]+Distinguished_Customer_ST[i])
  # calculations for other customers
  else:
     Ordinary_Customer_AT.append(Ordinary_Customer_IAT[i]+Ordinary_Customer_AT[i-1])
     Ordinary_Customer_SST.append(max(Ordinary_Customer_AT[i],Ordinary_Customer_CT[i-1]))
     Ordinary_Customer_WT.append(Ordinary_Customer_SST[i]-Ordinary_Customer_AT[i])
     Ordinary_Customer_CT.append(Ordinary_Customer_AT[i]+Ordinary_Customer_WT[i]+Ordinary_Customer_ST[i])

     Distinguished_Customer_AT.append(Distinguished_Customer_IAT[i]+Distinguished_Customer_AT[i-1])
     Distinguished_Customer_SST.append(max(Distinguished_Customer_AT[i],Distinguished_Customer_CT[i-1]))
     Distinguished_Customer_WT.append(Distinguished_Customer_SST[i]-Distinguished_Customer_AT[i])
     Distinguished_Customer_CT.append(Distinguished_Customer_AT[i]+Distinguished_Customer_WT[i]+Distinguished_Customer_ST[i])

#calculate avg waiting time for both types
Avg_Ordinary_Customer_WT = sum(Ordinary_Customer_WT)/len(Ordinary_Customer_WT)
Avg_Distinguished_Customer_WT = sum(Distinguished_Customer_WT)/len(Distinguished_Customer_WT)

print(Avg_Ordinary_Customer_WT)
print(Avg_Distinguished_Customer_WT)

import matplotlib.pyplot as plt
# graph for Ordinary Customer waiting time
plt.hist(Ordinary_Customer_WT)
plt.title('Ordinary_Customer_WT')
plt.show()

# graph for Distinguished Customer waiting time
plt.hist(Distinguished_Customer_WT)
plt.title('Distinguished_Customer_WT')
plt.show()